# docker-compose file for development

version: "3"
services:
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  # Access this container with `docker-compose exec crawler /bin/bash`
  crawler:
    build: ./crawler
    image: simple_search_engine__crawler
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./crawler:/container
    working_dir: /container
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017
      - INITIAL_URLS_FILE_PATH=/container/config/urls.txt
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

  api:
    build: ./api
    image: simple_search_engine__api
    depends_on:
      - mongodb
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/container
    working_dir: /container
    command: ["yarn", "dev"]
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/admin
      - PORT=3000
